-- TheGrudgeDB.lua
-- Generated by WhoDASH on 2026-03-22 04:40:16 UTC
-- DO NOT EDIT MANUALLY — this file is overwritten by SyncDAT addon sync.

TheGrudgeData = {
    ["version"] = 1,
    ["exported_at"] = 1774154416,
    ["exported_by"] = "WhoDASH",
    ["characters"] = {
        ["Icecrown:Amarigold"] = {
            ["name"]    = "Amarigold",
            ["realm"]   = "Icecrown",
            ["class"]   = "MAGE",
            ["faction"] = "Alliance",
            ["grudge_list"] = {
                {
                    ["name"]           = "Pludshinfive",
                    ["added_at"]       = 1773462622,
                    ["kill_count"]     = 1,
                    ["last_killed_at"] = 1773457055,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1773457055,
                            ["zone"]    = "Icecrown",
                            ["subzone"] = "",
                            ["spell"]   = "Typhoon",
                            ["damage"]  = 2166,
                        },
                    },
                },
                {
                    ["name"]           = "Babygahh",
                    ["added_at"]       = 1773108667,
                    ["kill_count"]     = 2,
                    ["last_killed_at"] = 1773107897,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1773107897,
                            ["zone"]    = "Stormwind City",
                            ["subzone"] = "Trade District",
                            ["spell"]   = "Howling Blast",
                            ["damage"]  = 5311,
                        },
                        {
                            ["ts"]      = 1772510666,
                            ["zone"]    = "Wintergrasp",
                            ["subzone"] = "",
                            ["spell"]   = "Frost Fever",
                            ["damage"]  = 807,
                        },
                    },
                },
                {
                    ["name"]           = "Bisao",
                    ["added_at"]       = 1773107330,
                    ["kill_count"]     = 2,
                    ["last_killed_at"] = 1773018244,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1773018244,
                            ["zone"]    = "Stormwind City",
                            ["subzone"] = "Trade District",
                            ["spell"]   = "Plague Strike",
                            ["damage"]  = 4187,
                        },
                        {
                            ["ts"]      = 1772508844,
                            ["zone"]    = "Wintergrasp",
                            ["subzone"] = "The Cauldron of Flames",
                            ["spell"]   = "Death and Decay",
                            ["damage"]  = 460,
                        },
                    },
                },
                {
                    ["name"]           = "Rubella",
                    ["added_at"]       = 1773107321,
                    ["kill_count"]     = 1,
                    ["last_killed_at"] = 1773106950,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1773106950,
                            ["zone"]    = "Stormwind City",
                            ["subzone"] = "Trade District",
                            ["spell"]   = "Howling Blast",
                            ["damage"]  = 5968,
                        },
                    },
                },
                {
                    ["name"]           = "Zilly",
                    ["added_at"]       = 1771727343,
                    ["kill_count"]     = 1,
                    ["last_killed_at"] = 1771384615,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1771384615,
                            ["zone"]    = "Tanaris",
                            ["subzone"] = "Gadgetzan",
                            ["spell"]   = "Shield of Righteousness",
                            ["damage"]  = 963,
                        },
                    },
                },
                {
                    ["name"]           = "Packdesix",
                    ["added_at"]       = 1771727338,
                    ["kill_count"]     = 4,
                    ["last_killed_at"] = 1771642729,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1771642729,
                            ["zone"]    = "Warsong Gulch",
                            ["subzone"] = "",
                            ["spell"]   = "Melee",
                            ["damage"]  = 3839,
                        },
                        {
                            ["ts"]      = 1771642207,
                            ["zone"]    = "Silverwing Hold",
                            ["subzone"] = "",
                            ["spell"]   = "Execute",
                            ["damage"]  = 3216,
                        },
                        {
                            ["ts"]      = 1771642018,
                            ["zone"]    = "Warsong Gulch",
                            ["subzone"] = "",
                            ["spell"]   = "Whirlwind",
                            ["damage"]  = 5429,
                        },
                        {
                            ["ts"]      = 1771641415,
                            ["zone"]    = "Warsong Gulch",
                            ["subzone"] = "Silverwing Hold",
                            ["spell"]   = "Whirlwind",
                            ["damage"]  = 5234,
                        },
                    },
                },
            },
        },
        ["Icecrown:Stouthearted"] = {
            ["name"]    = "Stouthearted",
            ["realm"]   = "Icecrown",
            ["class"]   = "PALADIN",
            ["faction"] = "Alliance",
            ["grudge_list"] = {
                {
                    ["name"]           = "Zikasales",
                    ["added_at"]       = 1772427056,
                    ["kill_count"]     = 1,
                    ["last_killed_at"] = 1771815450,
                    ["incidents"] = {
                        {
                            ["ts"]      = 1771815450,
                            ["zone"]    = "Tanaris",
                            ["subzone"] = "Gadgetzan",
                            ["spell"]   = "Crusader Strike",
                            ["damage"]  = 1938,
                        },
                    },
                },
            },
        },
    },
}
